In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from src.utils.paths import PROCESSED_DIR, RAW_DIR

sns.set_theme(style="whitegrid")
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.3f}'.format)

In [5]:
train_df = pd.read_csv(RAW_DIR / "train.csv")
eval_df = pd.read_csv(RAW_DIR / "eval.csv")


print('train:', train_df.shape, '| eval:', eval_df.shape)

train: (4930, 21) | eval: (1056, 21)

In [6]:
train_df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,6918-UMQCG,Female,0,No,No,5,Yes,No,Fiber optic,No,No,No,No,Yes,No,Month-to-month,No,Electronic check,80.200,384.25,No
1,4140-MUHUG,Female,1,No,No,3,Yes,No,Fiber optic,No,No,Yes,No,Yes,No,Month-to-month,Yes,Electronic check,86.850,220.95,Yes
2,5570-PTWEH,Female,0,Yes,No,3,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.150,216.75,Yes
3,2054-PJOCK,Female,0,No,No,60,Yes,Yes,DSL,No,No,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),80.550,4847.05,No
4,4315-MURBD,Female,0,No,No,12,Yes,No,Fiber optic,Yes,No,No,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),98.900,1120.95,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4925,0565-JUPYD,Male,0,No,No,63,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,No,One year,No,Credit card (automatic),104.500,6590.8,No
4926,8695-WDYEA,Male,0,No,No,1,Yes,No,DSL,Yes,No,No,No,No,No,Month-to-month,No,Mailed check,51.250,51.25,No
4927,6308-CQRBU,Female,0,Yes,No,71,Yes,Yes,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,Two year,No,Electronic check,109.250,7707.7,No
4928,3594-BDSOA,Female,0,Yes,No,24,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),20.400,482.8,No
4929,6490-FGZAT,Male,0,No,No,6,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.650,109.3,No

In [7]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4930 entries, 0 to 4929
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        4930 non-null   str
 1   gender            4930 non-null   str
 2   SeniorCitizen     4930 non-null   int64
 3   Partner           4930 non-null   str
 4   Dependents        4930 non-null   str
 5   tenure            4930 non-null   int64
 6   PhoneService      4930 non-null   str
 7   MultipleLines     4930 non-null   str
 8   InternetService   4930 non-null   str
 9   OnlineSecurity    4930 non-null   str
 10  OnlineBackup      4930 non-null   str
 11  DeviceProtection  4930 non-null   str
 12  TechSupport       4930 non-null   str
 13  StreamingTV       4930 non-null   str
 14  StreamingMovies   4930 non-null   str
 15  Contract          4930 non-null   str
 16  PaperlessBilling  4930 non-null   str
 17  PaymentMethod     4930 non-null   str
 18  MonthlyCharges    4930 non-null   float64
 19  TotalCharges      4930 non-null   str
 20  Churn             4930 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 809.0 KB

In [9]:
train_df.describe().T

                  count   mean    std    min    25%    50%    75%     max
SeniorCitizen  4930.000  0.161  0.368  0.000  0.000  0.000  0.000   1.000
tenure         4930.000 32.471 24.646  0.000  9.000 29.000 56.000  72.000
MonthlyCharges 4930.000 64.950 30.244 18.400 35.500 70.575 90.050 118.750

In [13]:
train_df.describe(exclude='number').T # type: ignore

                 count unique               top  freq
customerID        4930   4930        6918-UMQCG     1
gender            4930      2              Male  2478
Partner           4930      2                No  2558
Dependents        4930      2                No  3463
PhoneService      4930      2               Yes  4434
MultipleLines     4930      3                No  2347
InternetService   4930      3       Fiber optic  2177
OnlineSecurity    4930      3                No  2439
OnlineBackup      4930      3                No  2142
DeviceProtection  4930      3                No  2140
TechSupport       4930      3                No  2411
StreamingTV       4930      3               Yes  1941
StreamingMovies   4930      3                No  1931
Contract          4930      3    Month-to-month  2704
PaperlessBilling  4930      2               Yes  2920
PaymentMethod     4930      4  Electronic check  1654
TotalCharges      4930   4653                       7
Churn             4930      2                No  3622